- hosts: 127.0.0.1
  connection: local
  user: root
  gather_facts: false
  vars:
  tasks:
  - name: Gather all registered virtual machines
    local_action:
     module: vmware_vm_facts
     hostname: 192.168.102.100
     username: devops
     password: F1reF0x1$
